# =============================================================================
# File        : spyrun.toml
# Author      : yukimemi
# Last Change : 2024/09/16 19:27:27.
# =============================================================================

[vars]
base_local = '{{ cfg_dir }}\..'
base_remote = '{{ psf(arg="init.ps1") }}\user'

cfg_remote_dir = '{{ base_remote }}\cfg'
cfg_remote_path = '{{ base_remote }}\cfg\spyrun.toml'

hostname = '{{ env(arg="COMPUTERNAME") }}'

version = '20240916_192727'

funcs = '''
function log {
  param([string]$msg)
  trap { Write-Host "[log] Error $_" }
  $now = Get-Date -f "yyyy/MM/dd HH:mm:ss.fff"
  Write-Host "${now} ${msg}"
}
'''

trap_no_stop = '''
log "spy_name: [{{ spy_name }}]"
$ErrorActionPreference = "Stop"
trap {
  log "{{ spy_name }} Error ! $_"
}
'''

trap_stop = '''
log "spy_name: [{{ spy_name }}]"
$ErrorActionPreference = "Stop"
trap {
  log "{{ spy_name }} Error ! $_"
  "spy_name: [{{ spy_name }}] $_" | Set-Content "{{ stop_path }}"
}
'''

trap_stop_force = '''
log "spy_name: [{{ spy_name }}]"
$ErrorActionPreference = "Stop"
trap {
  log "{{ spy_name }} Error ! $_"
  "spy_name: [{{ spy_name }}] $_" | Set-Content "{{ stop_force_path }}"
}
'''

z_init_fn = '''
$script:stopFlg = $false
$copy = {
  param([string]$local, [string]$remote)
  $localHash = (Get-FileHash $local).Hash
  $remoteHash = (Get-FileHash $remote).Hash
  if ($remoteHash -ne $localHash) {
    if ($local -match "_backup") {
      $local = $local.Replace("_backup", "")
      $localHash = (Get-FileHash $local).Hash
      if ($localHash -eq $remoteHash) {
        return
      }
    }
    log "${remote} -> ${local}"
    New-Item -Force -ItemType Directory (Split-Path -Parent $local) | Out-Null
    Copy-Item -Force $remote $local
    $script:stopFlg = $true
  }
}
& $copy "{{ cfg_path }}" "{{ cfg_remote_path }}"
if ($script:stopFlg) {
  "spy_name: [{{ spy_name }}] stop flg is true" | Set-Content "{{ stop_force_path }}"
}
'''

[cfg]
stop_flg = '{{ base_local }}\stop.flg'

[log]
path = '{{ base_local }}\log\{{ cmd_stem }}.log'
level = 'info'

[init]
cmd = 'powershell'
arg = ['-NoProfile', '-Command', '''& {
  {{ funcs }}
  {{ trap_stop_force }}
  log "{{ version }}"
  {{ z_init_fn }}
}''']

# Update cfg toml when there is a change.
[[spys]]
name = 'update_toml'
input = '{{ cfg_remote_dir }}'
output = '{{ log_dir }}\{{ spy_name }}'
debounce = 5000
[[spys.patterns]]
pattern = '\.toml$'
cmd = 'powershell'
arg = ['-NoProfile', '-Command', '''& {
  {{ funcs }}
  {{ trap_stop_force }}
  {{ z_init_fn }}
}''']

# Execute under cmd/all/poll
[[spys]]
name = 'user_all_poll'
input = '{{ base_remote }}\cmd\all\poll'
output = '{{ base_remote }}\log\all\poll\{{ event_stem }}\{{ hostname }}'
debounce = 5000
[spys.poll]
interval = 10000
[spys.walk]
delay = [0, 60000]
pattern = '\.cmd$|\.exe$|\.bat$'

# Execute under cmd/all/notify
[[spys]]
name = 'user_all_notify'
input = '{{ base_remote }}\cmd\all\notify'
output = '{{ base_remote }}\log\all\notify\{{ event_stem }}\{{ hostname }}'
throttle = 5000
[spys.walk]
delay = [0, 60000]
pattern = '\.cmd$|\.exe$|\.bat$'

# Execute under cmd/host/poll
[[spys]]
name = 'user_host_poll'
input = '{{ base_remote }}\cmd\host\poll\{{ hostname }}'
output = '{{ base_remote }}\log\host\poll\{{ event_stem }}\{{ hostname }}'
debounce = 5000
[spys.poll]
interval = 10000
[spys.walk]
delay = [0, 60000]
pattern = '\.cmd$|\.exe$|\.bat$'

# Execute under cmd/host/notify
[[spys]]
name = 'user_host_notify'
input = '{{ base_remote }}\cmd\host\notify\{{ hostname }}'
output = '{{ base_remote }}\log\host\notify\{{ event_stem }}\{{ hostname }}'
throttle = 5000
[spys.walk]
pattern = '\.cmd$|\.exe$|\.bat$'

