# =============================================================================
# File        : spyrun.toml
# Author      : yukimemi
# Last Change : 2024/11/10 17:27:56.
# =============================================================================

[vars]
base_local = '{{ cfg_dir }}\..'
hostname = '{{ env(arg="COMPUTERNAME") }}'
version = '20241110_172756'

funcs = '''
function log {
  param([string]$msg)
  trap { Write-Host "[log] Error $_" }
  $now = Get-Date -f "yyyy/MM/dd HH:mm:ss.fff"
  Write-Host "${now} ${msg}"
}
'''

trap_no_stop = '''
log "spy_name: [{{ spy_name }}]"
$ErrorActionPreference = "Stop"
trap {
  log "{{ spy_name }} Error ! $_"
}
'''

trap_stop = '''
log "spy_name: [{{ spy_name }}]"
$ErrorActionPreference = "Stop"
trap {
  log "{{ spy_name }} Error ! $_"
  "spy_name: [{{ spy_name }}] $_" | Set-Content -Encoding utf8 "{{ stop_path }}"
}
'''

trap_stop_force = '''
log "spy_name: [{{ spy_name }}]"
$ErrorActionPreference = "Stop"
trap {
  log "{{ spy_name }} Error ! $_"
  "spy_name: [{{ spy_name }}] $_" | Set-Content -Encoding utf8 "{{ stop_force_path }}"
}
'''

[cfg]
stop_flg = '{{ base_local }}\stop.flg'

[log]
path = '{{ base_local }}\log\{{ cmd_stem }}.log'
level = 'info'

[init]
cmd = 'powershell'
arg = ['-NoProfile', '-Command', '''& {
  {{ funcs }}
  {{ trap_stop_force }}
  log "{{ version }}"
}''']

# Update cfg toml when there is a change.
[[spys]]
name = 'update_cfg'
input = '{{ cfg_dir }}'
output = '{{ log_dir }}\{{ spy_name }}\{{ event_stem }}'
debounce = 5000
[[spys.patterns]]
pattern = '\.toml$'
cmd = 'powershell'
arg = ['-NoProfile', '-Command', '''& {
  {{ funcs }}
  {{ trap_stop_force }}
  throw "Update config {{ event_path }}"
}''']

# Execute cmd/global
[[spys]]
name = 'cmd_global'
input = '{{ base_local }}\cmd\global'
output = '{{ log_dir }}\{{ spy_name }}\{{ event_stem }}'
debounce = 5000
[spys.poll]
interval = 10000
[spys.walk]
delay = [0, 60000]
pattern = '\.cmd$|\.exe$|\.bat$'
# Execute cmd/local
[[spys]]
name = 'cmd_local'
input = '{{ base_local }}\cmd\local\\{{ hostname }}'
output = '{{ log_dir }}\{{ spy_name }}\{{ event_stem }}'
debounce = 5000
[spys.poll]
interval = 10000
[spys.walk]
delay = [0, 60000]
pattern = '\.cmd$|\.exe$|\.bat$'
